import { Link } from 'react-router-dom';
import { IconArrowRight, IconCheck, IconHome2, IconMapPin, IconRulerMeasure, IconShieldCheck } from '@tabler/icons-react';

const catalogueUrl = '/catalogue?p_listing_types=SALE&p_property_types=HOUSE&p_location_search=Tirunelveli';

const houseTypes = [
    ['2 BHK Houses for Sale in Tirunelveli', 'Ideal for couples, small families and first-time homebuyers, 2 BHK houses offer a practical balance of space, comfort and affordability.'],
    ['3 BHK Houses for Sale in Tirunelveli', 'A great choice for growing families, 3 BHK houses provide additional bedrooms and living space for comfortable family living.'],
    ['4 BHK Houses for Sale in Tirunelveli', 'For larger families looking for generous living areas, multiple bedrooms and more space, 4 BHK independent houses can be an excellent option.'],
    ['Independent Houses for Sale in Tirunelveli', 'Independent homes offer greater privacy, dedicated space and the flexibility that many homebuyers look for. Explore independent houses in established and developing residential neighbourhoods.'],
    ['Ready-to-Move Houses in Tirunelveli', 'If you want to move into your new home without waiting for construction to be completed, ready-to-move houses can provide a convenient option.'],
];

const localities = ['KTC Nagar', 'Palayamkottai', 'Reddiarpatti', 'Perumalpuram', 'Tuckerammalpuram', 'NGO Colony', 'Thirunagar', 'Melapalayam', 'Thachanallur', 'Maharaja Nagar'];
const comparisonPoints = ['Location and neighbourhood', 'Property type', 'BHK configuration', 'Built-up area', 'Plot size', 'Price', 'Ready-to-move or resale status', 'Parking and other available features'];

const faqs = [
    ['What types of houses are available for sale in Tirunelveli?', 'You can find different types of residential properties, including 2 BHK, 3 BHK and 4 BHK independent houses, family homes and ready-to-move properties.'],
    ['Which are popular areas to buy a house in Tirunelveli?', 'Popular residential locations include KTC Nagar, Palayamkottai, Reddiarpatti, Perumalpuram, Tuckerammalpuram, NGO Colony and other established neighbourhoods.'],
    ['Can I find 2 BHK houses for sale in Tirunelveli?', 'Yes. 2 BHK houses are among the commonly listed residential options in Tirunelveli and are suitable for small families, couples and first-time buyers.'],
    ['Are ready-to-move houses available in Tirunelveli?', 'Yes, ready-to-move independent houses are available in several Tirunelveli localities. Availability changes regularly, so buyers should check the latest property listings for current options.'],
    ['How can I find the right house in Tirunelveli?', 'Start by deciding your budget, preferred location, BHK requirement and desired plot or built-up area. You can then compare suitable properties on Veedu 360 and shortlist homes that match your needs.'],
];

function HousesForSaleTirunelveli() {
    return (
        <div className="min-h-screen bg-gray-50">
            <title>Houses for Sale in Tirunelveli | Veedu 360</title>

            <section className="relative h-[410px] bg-cover bg-center sm:h-[450px] md:h-[500px]" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=1920&q=85')" }}>
                <div className="absolute inset-0 bg-[#1E3347]/70" />
                <div className="relative z-10 mx-auto flex h-full max-w-7xl items-center px-4 sm:px-6"><div className="max-w-3xl"><div className="mb-4 inline-flex items-center gap-1.5 rounded-full bg-white/15 px-3 py-1.5 text-xs font-semibold text-white backdrop-blur-sm"><IconMapPin size={15} className="text-[#f4ca42]" /> Tirunelveli, Tamil Nadu</div><h1 className="text-3xl font-extrabold leading-tight tracking-tight text-white sm:text-4xl md:text-5xl">Houses for Sale in Tirunelveli</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-gray-100 sm:text-base">Looking for houses for sale in Tirunelveli? Veedu 360 helps you discover residential houses that match your budget, preferred location and lifestyle.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#D9A619] px-5 py-2.5 text-sm font-bold text-[#2C4964] no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#f0c13d]">Explore houses for sale <IconArrowRight size={17} /></Link></div></div>
            </section>

            <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="grid items-center gap-10 md:grid-cols-2 md:gap-12"><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Find Your Ideal House for Sale in Tirunelveli</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Find Your Ideal House for Sale in Tirunelveli</h2><p className="mt-4 text-sm leading-7 text-gray-600 sm:text-base">Looking for houses for sale in Tirunelveli? Veedu 360 helps you discover residential houses that match your budget, preferred location and lifestyle. Explore a range of independent houses, family homes and ready-to-move properties across popular residential areas in Tirunelveli.</p><p className="mt-4 text-sm leading-7 text-gray-600">Whether you are searching for a compact 2 BHK home, a spacious 3 BHK house or a larger family residence, Veedu 360 makes it easier to find a home that suits your requirements.</p><p className="mt-4 text-sm leading-7 text-gray-600">Buying a house is an important decision, and choosing the right location and property can make all the difference. With Veedu 360, you can explore houses in and around Tirunelveli based on your preferred locality, configuration, budget and property requirements.</p><p className="mt-4 text-sm leading-7 text-gray-600">Our listings can help you compare different residential options and find a property that fits your lifestyle and long-term plans.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#2C4964] px-6 py-2.5 text-sm font-bold text-white no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#1E3347] hover:shadow-lg">Browse Houses <IconArrowRight size={17} /></Link></div><div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-[#2C4964] text-white"><IconHome2 size={25} /></div><p className="mt-5 text-sm leading-7 text-gray-600">Whether your priority is affordability, location, built-up area or the number of bedrooms, Veedu 360 helps you explore different house options in Tirunelveli.</p></div></div></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="text-center"><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Types of Houses Available in Tirunelveli</span><h2 className="mt-3 text-3xl font-bold text-[#2C4964]">Types of Houses Available in Tirunelveli</h2></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{houseTypes.map(([name, description]) => <article key={name} className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-[#2C4964] text-white"><IconHome2 size={24} /></div><h3 className="mt-5 text-xl font-bold text-gray-800">{name}</h3><p className="mt-3 text-sm leading-7 text-gray-600">{description}</p><Link to={catalogueUrl} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#2C4964] no-underline hover:text-[#D9A619]">Explore options <IconArrowRight size={16} /></Link></article>)}</div></div></section>

            <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="grid gap-8 md:grid-cols-[.85fr_1.15fr] md:items-end"><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Popular Areas to Buy Houses in Tirunelveli</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Popular Areas to Buy Houses in Tirunelveli</h2></div><p className="text-sm leading-7 text-gray-600">Tirunelveli offers residential options across established neighbourhoods as well as developing areas. Depending on your budget and requirements, you can explore houses in locations such as:</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{localities.map((area) => <article key={area} className="flex items-center gap-3 rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><IconMapPin size={19} className="shrink-0 text-[#D9A619]" /><h3 className="text-sm font-bold text-gray-800">{area}</h3></article>)}</div><p className="mt-6 text-sm leading-7 text-gray-600">Property availability and prices can vary by locality, plot size, built-up area, house configuration and property condition.</p></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 md:grid-cols-2 md:items-center"><div className="relative h-64 overflow-hidden rounded-2xl shadow-lg md:h-[360px]"><img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85" alt="Independent house for sale" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-black/10" /></div><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Why Buy a House in Tirunelveli?</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Why Buy a House in Tirunelveli?</h2><p className="mt-4 text-sm leading-7 text-gray-600">Tirunelveli is an established city with a growing residential market and a variety of housing options. Homebuyers can choose from properties suited to different budgets and family sizes, from smaller 1 and 2 BHK homes to spacious 3 and 4 BHK houses.</p><p className="mt-4 text-sm leading-7 text-gray-600">Choosing a home in the right neighbourhood can also provide convenient access to schools, hospitals, shopping areas, workplaces and everyday amenities.</p></div></div></section>

            <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="grid gap-8 md:grid-cols-2"><div className="rounded-2xl bg-[#2C4964] p-7 text-white sm:p-8"><IconRulerMeasure className="text-[#D9A619]" size={32} /><h2 className="mt-5 text-2xl font-bold">Find Houses That Match Your Budget</h2><p className="mt-3 text-sm leading-7 text-slate-200">Whether your priority is affordability, location, built-up area or the number of bedrooms, Veedu 360 helps you explore different house options in Tirunelveli.</p><p className="mt-4 text-sm font-semibold leading-7 text-white">You can compare properties based on:</p><div className="mt-4 grid gap-3 text-sm text-slate-200 sm:grid-cols-2">{comparisonPoints.map((item) => <div key={item} className="flex gap-2"><IconCheck size={17} className="shrink-0 text-[#D9A619]" />{item}</div>)}</div></div><div className="rounded-2xl border border-gray-200 bg-white p-7 shadow-sm sm:p-8"><IconShieldCheck className="text-[#2C4964]" size={32} /><h2 className="mt-5 text-2xl font-bold text-gray-800">Buy Your Dream House in Tirunelveli with Veedu 360</h2><p className="mt-3 text-sm leading-7 text-gray-600">Your search for the right home starts with finding the right property. Veedu 360 brings together residential property options to help buyers discover houses for sale in Tirunelveli more conveniently.</p><p className="mt-4 text-sm leading-7 text-gray-600">Explore available properties, shortlist homes that meet your requirements and take the next step towards owning your dream home in Tirunelveli.</p></div></div></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="text-center"><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Frequently Asked Questions</span><h2 className="mt-3 text-3xl font-bold text-[#2C4964]">Frequently Asked Questions</h2></div><div className="mt-8 divide-y divide-gray-200 rounded-xl border border-gray-200 bg-white px-5">{faqs.map(([question, answer], index) => <details key={question} className="group py-4"><summary className="cursor-pointer list-none pr-6 text-sm font-bold text-gray-800">{index + 1}. {question}<span className="float-right text-xl font-normal text-[#2C4964] transition-transform group-open:rotate-45">+</span></summary><p className="pt-3 pr-4 text-sm leading-6 text-gray-600">{answer}</p></details>)}</div></div></section>

            <section className="px-4 py-14 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl rounded-2xl bg-[#2C4964] px-6 py-10 text-center shadow-lg sm:px-10"><h2 className="text-3xl font-bold text-white">Buy Your Dream House in Tirunelveli with Veedu 360</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-slate-200">Looking for your next home? Explore houses for sale in Tirunelveli with Veedu 360 today.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#D9A619] px-6 py-2.5 text-sm font-bold text-[#2C4964] no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#f0c13d]">Explore houses for sale <IconArrowRight size={17} /></Link></div></section>
        </div>
    );
}

export default HousesForSaleTirunelveli;
