import { Link } from 'react-router-dom';
import { IconArrowRight, IconCheck, IconMapPin, IconRulerMeasure, IconRoad, IconShieldCheck, IconTree } from '@tabler/icons-react';

const catalogueUrl = '/catalogue?p_listing_types=SALE&p_property_types=LAND&p_location_search=Tirunelveli';

const plotFeatures = ['Plot size and dimensions', 'Preferred location', 'Residential surroundings', 'Road connectivity', 'Budget', 'Future development potential', 'Plot orientation and accessibility', 'New and resale land options'];
const localities = ['Palayamkottai', 'Reddiarpatti', 'KTC Nagar', 'Krishnapuram', 'Nanguneri', 'Gangaikondan', 'Vannarpettai', 'Surrounding Tirunelveli localities'];
const checks = [
    ['Location & Connectivity', 'Check access roads, nearby schools, hospitals, shopping areas, workplaces and other everyday conveniences.'],
    ['Plot Size & Shape', 'Make sure the dimensions work for your proposed house plan and parking requirements.'],
    ['Title & Ownership', 'Verify ownership records and ensure the seller has the legal right to sell the property.'],
    ['Approvals & Documents', 'Check applicable layout approvals, patta, encumbrance details and other relevant property documents with qualified professionals.'],
    ['Road Access & Utilities', 'Confirm road access and the availability or feasibility of electricity, water and drainage connections.'],
    ['Future Development', 'Consider surrounding development and planned infrastructure, without treating future projects as guaranteed returns.'],
];
const faqs = [
    ['Where can I find plots for sale in Tirunelveli?', 'You can explore residential plots across Tirunelveli and surrounding localities, including areas such as Palayamkottai, Reddiarpatti, KTC Nagar, Krishnapuram and Nanguneri.'],
    ['Are plots in Tirunelveli suitable for building a house?', "Residential plots can be suitable for house construction, subject to the property's zoning, approvals, applicable building regulations and other legal requirements."],
    ['What documents should I check before buying a plot?', 'Important documents may include title documents, patta, encumbrance records, approved layout documents and other applicable approvals.'],
    ['Can I buy a plot as an investment?', 'A plot may be considered as a long-term property investment, but potential returns depend on factors such as location, demand, infrastructure, development and market conditions.'],
    ['How do I choose the best plot in Tirunelveli?', 'Compare location, plot size, road access, surrounding development, documentation, approvals and overall price before making your decision.'],
];

function PlotsForSaleTirunelveli() {
    return (
        <div className="min-h-screen bg-gray-50">
            <title>Plots for Sale in Tirunelveli | Veedu 360</title>

            <section className="relative h-[410px] bg-cover bg-center sm:h-[450px] md:h-[500px]" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1920&q=85')" }}>
                <div className="absolute inset-0 bg-[#1E3347]/70" />
                <div className="relative z-10 mx-auto flex h-full max-w-7xl items-center px-4 sm:px-6"><div className="max-w-3xl"><div className="mb-4 inline-flex items-center gap-1.5 rounded-full bg-white/15 px-3 py-1.5 text-xs font-semibold text-white backdrop-blur-sm"><IconMapPin size={15} className="text-[#f4ca42]" /> Tirunelveli, Tamil Nadu</div><h1 className="text-3xl font-extrabold leading-tight tracking-tight text-white sm:text-4xl md:text-5xl">Plots for Sale in Tirunelveli - Build Your Future with Veedu 360</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-gray-100 sm:text-base">Looking for the right plots for sale in Tirunelveli to build your dream home or make a smart property investment?</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#D9A619] px-5 py-2.5 text-sm font-bold text-[#2C4964] no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#f0c13d]">Explore plots for sale <IconArrowRight size={17} /></Link></div></div>
            </section>

            <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="grid items-center gap-10 md:grid-cols-2 md:gap-12"><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Find the Right Residential Plot in Tirunelveli</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Find the Right Residential Plot in Tirunelveli</h2><p className="mt-4 text-sm leading-7 text-gray-600 sm:text-base">Looking for the right plots for sale in Tirunelveli to build your dream home or make a smart property investment? Veedu 360 helps you discover residential plots and land options in and around Tirunelveli, making it easier to find a location that suits your budget, lifestyle and future plans.</p><p className="mt-4 text-sm leading-7 text-gray-600">With residential plots available across different sizes, locations and price ranges, Tirunelveli offers opportunities for both first-time buyers and long-term investors. Current property listings in the market include options in areas such as Palayamkottai, Reddiarpatti, KTC Nagar, Krishnapuram, Nanguneri and other developing locations.</p><p className="mt-4 text-sm leading-7 text-gray-600">A plot gives you the freedom to create a home according to your own requirements. Whether you are planning to construct a compact family home, a spacious independent house or simply looking for land with long-term potential, choosing the right plot is the first step.</p></div><div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-[#2C4964] text-white"><IconRulerMeasure size={25} /></div><p className="mt-5 text-sm font-semibold leading-7 text-gray-700">At Veedu 360, explore property options based on:</p><div className="mt-4 grid gap-3 text-sm text-gray-600 sm:grid-cols-2">{plotFeatures.map((item) => <div key={item} className="flex gap-2"><IconCheck size={17} className="shrink-0 text-[#D9A619]" />{item}</div>)}</div></div></div></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="text-center"><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Why Buy a Plot in Tirunelveli?</span><h2 className="mt-3 text-3xl font-bold text-[#2C4964]">Why Buy a Plot in Tirunelveli?</h2><p className="mx-auto mt-3 max-w-3xl text-sm leading-7 text-gray-500">Tirunelveli continues to attract homebuyers and property investors looking for residential land in established as well as developing neighbourhoods. The availability of plots across different sizes makes it possible to choose land according to your construction plans and budget.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3"><article className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><IconTree className="text-[#2C4964]" size={28} /><h3 className="mt-5 text-xl font-bold text-gray-800">Build Your Dream Home</h3><p className="mt-3 text-sm leading-7 text-gray-600">Buying a plot allows you to design and construct your home based on your family's needs. You can plan the number of rooms, parking space, garden area, floors and other features according to the plot and applicable regulations.</p></article><article className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><IconMapPin className="text-[#2C4964]" size={28} /><h3 className="mt-5 text-xl font-bold text-gray-800">Choose a Location That Fits Your Lifestyle</h3><p className="mt-3 text-sm leading-7 text-gray-600">From established residential neighbourhoods to developing areas around Tirunelveli, buyers can explore different locations depending on their priorities. Areas such as Palayamkottai, Reddiarpatti, KTC Nagar, Krishnapuram and surrounding localities feature residential land listings.</p></article><article className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><IconRoad className="text-[#2C4964]" size={28} /><h3 className="mt-5 text-xl font-bold text-gray-800">Plan for Long-Term Value</h3><p className="mt-3 text-sm leading-7 text-gray-600">A well-located plot can be considered for long-term property investment, particularly when surrounding infrastructure and residential development continue to grow. However, buyers should evaluate location, title, approvals, access and other legal factors before making an investment decision.</p></article></div></div></section>

            <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="grid gap-8 md:grid-cols-[.85fr_1.15fr] md:items-end"><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Explore Plots for Sale in Different Locations</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Explore Plots for Sale in Different Locations</h2></div><p className="text-sm leading-7 text-gray-600">Veedu 360 makes it easier to explore plot options across Tirunelveli and nearby areas. Whether you are searching for a plot close to established residential communities or land in a developing locality, compare available properties and identify the option that matches your requirements.</p></div><p className="mt-6 text-sm font-semibold leading-7 text-gray-700">Some areas where buyers can explore residential land include:</p><div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{localities.map((area) => <article key={area} className="flex items-center gap-3 rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><IconMapPin size={19} className="shrink-0 text-[#D9A619]" /><h3 className="text-sm font-bold text-gray-800">{area}</h3></article>)}</div><p className="mt-6 text-sm leading-7 text-gray-600">Property availability, prices and plot sizes can vary considerably by location. Current listings show options ranging from smaller residential plots to larger parcels of land, giving buyers a broad selection.</p></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="mx-auto max-w-3xl text-center"><span className="text-xs font-bold uppercase tracking-widest text-gray-500">What to Check Before Buying a Plot</span><h2 className="mt-3 text-3xl font-bold text-[#2C4964]">What to Check Before Buying a Plot</h2><p className="mt-3 text-sm leading-7 text-gray-500">Before finalising a residential plot, take time to verify the important property details. Buyers should consider:</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{checks.map(([title, description]) => <article key={title} className="rounded-xl border border-gray-200 bg-white p-5 shadow-sm"><IconShieldCheck className="text-[#D9A619]" size={23} /><h3 className="mt-4 text-lg font-bold text-gray-800">{title}</h3><p className="mt-2 text-sm leading-6 text-gray-600">{description}</p></article>)}</div></div></section>

            <section className="px-4 py-14 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl rounded-2xl bg-[#2C4964] px-6 py-10 text-center shadow-lg sm:px-10"><h2 className="text-3xl font-bold text-white">Find Your Ideal Plot with Veedu 360</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-slate-200">Veedu 360 brings together plot and land opportunities in Tirunelveli so buyers can explore properties, compare locations and take the next step towards owning their own space.</p><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-slate-200">Whether you are looking for residential plots in Tirunelveli, land for sale in Tirunelveli, or a plot to build your future home, explore the available options with Veedu 360.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#D9A619] px-6 py-2.5 text-sm font-bold text-[#2C4964] no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#f0c13d]">Explore plots for sale <IconArrowRight size={17} /></Link></div></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="text-center"><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Frequently Asked Questions</span><h2 className="mt-3 text-3xl font-bold text-[#2C4964]">Frequently Asked Questions</h2></div><div className="mt-8 divide-y divide-gray-200 rounded-xl border border-gray-200 bg-white px-5">{faqs.map(([question, answer], index) => <details key={question} className="group py-4"><summary className="cursor-pointer list-none pr-6 text-sm font-bold text-gray-800">{index + 1}. {question}<span className="float-right text-xl font-normal text-[#2C4964] transition-transform group-open:rotate-45">+</span></summary><p className="pt-3 pr-4 text-sm leading-6 text-gray-600">{answer}</p></details>)}</div></div></section>

            <section className="px-4 py-14 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl rounded-2xl bg-[#2C4964] px-6 py-10 text-center shadow-lg sm:px-10"><h2 className="text-3xl font-bold text-white">Find Plots for Sale in Tirunelveli with Veedu 360</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-7 text-slate-200">Explore available properties and take the first step towards owning land in Tirunelveli. Search, compare and find your ideal plot with Veedu 360.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#D9A619] px-6 py-2.5 text-sm font-bold text-[#2C4964] no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#f0c13d]">Explore plots for sale <IconArrowRight size={17} /></Link></div></section>
        </div>
    );
}

export default PlotsForSaleTirunelveli;
