import { Link } from 'react-router-dom';
import { IconArrowRight, IconCheck, IconHome2, IconMapPin, IconTrees } from '@tabler/icons-react';

const catalogueUrl = '/catalogue?p_listing_types=SALE&p_property_types=HOUSE&p_house_types=INDEPENDENT_VILLA&p_location_search=Tirunelveli';

const villaTypes = [
    ['2 BHK Villas for Sale in Tirunelveli', 'A 2 BHK villa is an excellent choice for couples, small families and first-time homebuyers. These villas provide practical living spaces while offering the privacy and independence of an individual home.'],
    ['3 BHK Villas for Sale in Tirunelveli', 'If you need additional bedrooms, living space and room for your family to grow, explore 3 BHK villas in Tirunelveli. These homes are suitable for families seeking a comfortable combination of space, functionality and privacy.'],
    ['4 BHK Villas for Sale in Tirunelveli', 'For larger families or buyers looking for a more spacious lifestyle, 4 BHK villas offer generous interiors, multiple bedrooms and greater flexibility. Explore premium and independent villa options based on your preferred location and budget.'],
];

const localities = ['KTC Nagar', 'Palayamkottai', 'NGO Colony', 'Thyagaraja Nagar', 'Perumal Puram', 'Suthamalli', 'Manur', 'Tirunelveli Junction'];
const villaBenefits = ['More privacy than apartment living', 'Spacious bedrooms and living areas', 'Dedicated parking space', 'Outdoor or garden space', 'Greater freedom to customise the home', 'A comfortable environment for family living', 'Long-term residential value'];

const faqs = [
    ['Where can I find villas for sale in Tirunelveli?', 'Villas are available across several areas of Tirunelveli and the surrounding region. Popular property-search locations include KTC Nagar, Palayamkottai, NGO Colony, Thyagaraja Nagar and other developing residential areas.'],
    ['Are 2 BHK and 3 BHK villas available in Tirunelveli?', 'Yes. Villa listings in Tirunelveli include different configurations, including 2 BHK, 3 BHK and larger villas, depending on the project and locality.'],
    ['Why should I buy an independent villa?', 'Independent villas offer greater privacy, more usable space and the feeling of owning your own home. They can also provide features such as parking, terraces and outdoor areas depending on the property.'],
    ['How do I choose the right villa in Tirunelveli?', 'Consider your budget, preferred locality, villa size, number of bedrooms, construction quality, parking, accessibility and nearby schools, hospitals, shops and other essential facilities before making a decision.'],
    ['Can I find villas in different price ranges?', 'Yes. Villa prices vary considerably based on location, land area, built-up area, configuration, age, amenities and other property features. Current listings in Tirunelveli show a wide range of villa options.'],
    ['Why choose Veedu 360?', 'Veedu 360 makes it easier for buyers to discover and compare residential properties in Tirunelveli. Explore available villa listings and find property options that match your requirements, location preference and budget.'],
];

function VillasForSaleTirunelveli() {
    return (
        <div className="min-h-screen bg-gray-50">
            <title>Villas for Sale in Tirunelveli | Veedu 360</title>

            <section className="relative h-[410px] bg-cover bg-center sm:h-[450px] md:h-[500px]" style={{ backgroundImage: "url('https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1920&q=85')" }}>
                <div className="absolute inset-0 bg-[#1E3347]/70" />
                <div className="relative z-10 mx-auto flex h-full max-w-7xl items-center px-4 sm:px-6"><div className="max-w-3xl"><div className="mb-4 inline-flex items-center gap-1.5 rounded-full bg-white/15 px-3 py-1.5 text-xs font-semibold text-white backdrop-blur-sm"><IconMapPin size={15} className="text-[#f4ca42]" /> Tirunelveli, Tamil Nadu</div><h1 className="text-3xl font-extrabold leading-tight tracking-tight text-white sm:text-4xl md:text-5xl">Villas for Sale in Tirunelveli</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-gray-100 sm:text-base">Looking for the perfect villa for your family in Tirunelveli? Veedu 360 helps you discover carefully selected villas for sale in Tirunelveli.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#D9A619] px-5 py-2.5 text-sm font-bold text-[#2C4964] no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#f0c13d]">Browse villas for sale <IconArrowRight size={17} /></Link></div></div>
            </section>

            <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="grid items-center gap-10 md:grid-cols-2 md:gap-12"><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Explore Villas for Sale in Tirunelveli</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Explore Villas for Sale in Tirunelveli</h2><p className="mt-4 text-sm leading-7 text-gray-600 sm:text-base">Looking for the perfect villa for your family in Tirunelveli? Veedu 360 helps you discover carefully selected villas for sale in Tirunelveli, offering comfortable living spaces, modern features, privacy and convenient locations. Whether you are searching for a cosy 2 BHK villa, a spacious 3 BHK villa or a premium 4 BHK villa, explore property options that suit your lifestyle and budget.</p><p className="mt-4 text-sm leading-7 text-gray-600">With growing residential development across Tirunelveli and surrounding areas, independent villas are an attractive choice for families looking for more space and privacy than a typical apartment.</p><p className="mt-4 text-sm leading-7 text-gray-600">At Veedu 360, you can explore a variety of villa properties designed for different family requirements and budgets. From compact homes for small families to spacious independent villas for larger families, our listings help make your property search easier.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#2C4964] px-6 py-2.5 text-sm font-bold text-white no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#1E3347] hover:shadow-lg">Explore villa listings <IconArrowRight size={17} /></Link></div><div className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm sm:p-7"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-[#2C4964] text-white"><IconHome2 size={25} /></div><p className="mt-5 text-sm leading-7 text-gray-600">Whether you are looking for an affordable villa in Tirunelveli, a luxury villa, an independent villa, or a spacious family home, explore the available properties on Veedu 360 and take the next step towards owning your dream home.</p></div></div></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="text-center"><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Villa configurations</span><h2 className="mt-3 text-3xl font-bold text-[#2C4964]">Explore Villas for Sale in Tirunelveli</h2></div><div className="mt-10 grid gap-6 md:grid-cols-3">{villaTypes.map(([name, description]) => <article key={name} className="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-[#2C4964] text-white"><IconHome2 size={24} /></div><h3 className="mt-5 text-xl font-bold text-gray-800">{name}</h3><p className="mt-3 text-sm leading-7 text-gray-600">{description}</p><Link to={catalogueUrl} className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-[#2C4964] no-underline hover:text-[#D9A619]">Explore options <IconArrowRight size={16} /></Link></article>)}</div></div></section>

            <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 md:py-20"><div className="grid gap-8 md:grid-cols-[.85fr_1.15fr] md:items-end"><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Find Villas in Popular Areas of Tirunelveli</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Find Villas in Popular Areas of Tirunelveli</h2></div><p className="text-sm leading-7 text-gray-600">Choose a villa in a location that fits your daily lifestyle. Popular property-search areas in and around Tirunelveli include KTC Nagar, Palayamkottai, NGO Colony, Thyagaraja Nagar, Perumal Puram, Suthamalli, Manur and Tirunelveli Junction. Availability and property types can vary by locality.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{localities.map((area) => <article key={area} className="flex items-center gap-3 rounded-xl border border-gray-200 bg-white p-4 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><IconMapPin size={19} className="shrink-0 text-[#D9A619]" /><h3 className="text-sm font-bold text-gray-800">{area}</h3></article>)}</div><p className="mt-6 text-sm leading-7 text-gray-600">Whether you prefer a well-established residential neighbourhood or a developing area with new housing options, Veedu 360 makes it easier to explore villas across Tirunelveli.</p></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 md:grid-cols-2 md:items-center"><div className="relative h-64 overflow-hidden rounded-2xl shadow-lg md:h-[360px]"><img src="https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85" alt="Independent villa for sale" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-black/10" /></div><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Why Choose a Villa in Tirunelveli?</span><h2 className="mt-3 text-3xl font-bold leading-tight text-[#2C4964]">Why Choose a Villa in Tirunelveli?</h2><p className="mt-4 text-sm leading-7 text-gray-600">Buying a villa gives you the advantages of independent homeownership along with greater privacy and space. Depending on the property, you may have dedicated parking, private outdoor areas, terraces and the flexibility to personalise your home.</p><p className="mt-4 text-sm font-semibold leading-7 text-gray-700">A villa can be particularly suitable for families who want:</p><div className="mt-4 grid gap-3 text-sm text-gray-600 sm:grid-cols-2">{villaBenefits.map((item) => <div key={item} className="flex gap-2"><IconCheck size={17} className="shrink-0 text-[#D9A619]" />{item}</div>)}</div></div></div></section>

            <section className="px-4 py-14 sm:px-6 md:py-20"><div className="mx-auto max-w-7xl rounded-2xl bg-[#2C4964] px-6 py-10 text-center shadow-lg sm:px-10"><IconTrees className="mx-auto text-[#D9A619]" size={32} /><h2 className="mt-4 text-3xl font-bold text-white">Find Your Dream Villa with Veedu 360</h2><p className="mx-auto mt-3 max-w-3xl text-sm leading-7 text-slate-200">Searching for a villa for sale in Tirunelveli does not have to be complicated. Veedu 360 brings property options together in one place so you can compare villas based on location, configuration, budget and lifestyle requirements.</p><p className="mx-auto mt-3 max-w-3xl text-sm leading-7 text-slate-200">Whether you are looking for an affordable villa in Tirunelveli, a luxury villa, an independent villa, or a spacious family home, explore the available properties on Veedu 360 and take the next step towards owning your dream home.</p><p className="mx-auto mt-3 max-w-3xl text-sm leading-7 text-slate-200">Browse villas for sale in Tirunelveli with Veedu 360 and find a home that fits your family's needs.</p><Link to={catalogueUrl} className="mt-6 inline-flex items-center justify-center gap-2 rounded-lg bg-[#D9A619] px-6 py-2.5 text-sm font-bold text-[#2C4964] no-underline shadow-md transition-all hover:-translate-y-0.5 hover:bg-[#f0c13d]">Browse villas for sale <IconArrowRight size={17} /></Link></div></section>

            <section className="bg-white py-14 md:py-20"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="text-center"><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Frequently Asked Questions</span><h2 className="mt-3 text-3xl font-bold text-[#2C4964]">Frequently Asked Questions</h2></div><div className="mt-8 divide-y divide-gray-200 rounded-xl border border-gray-200 bg-white px-5">{faqs.map(([question, answer], index) => <details key={question} className="group py-4"><summary className="cursor-pointer list-none pr-6 text-sm font-bold text-gray-800">{index + 1}. {question}<span className="float-right text-xl font-normal text-[#2C4964] transition-transform group-open:rotate-45">+</span></summary><p className="pt-3 pr-4 text-sm leading-6 text-gray-600">{answer}</p></details>)}</div></div></section>
        </div>
    );
}

export default VillasForSaleTirunelveli;
